## Autor:

version: "3"
services:
  httpsapp:
    build:
      context: ./app
      dockerfile: Dockerfile_With_Cert
    ports:
      - "5001:5001"
    volumes:
      - ./CA/certificate.pem:/app/certificate.pem
      - ./CA/private_key.pem:/app/private_key.pem
  httpapp:
    build:
      context: ./app  
      dockerfile: Dockerfile
    ports:
      - "80:80"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8081:80