version: "3"
services:
  httpsapp:
    build:
      context: ./app
      dockerfile: Dockerfile_With_Cert
    ports:
      - "5001:5001"
    volumes:
      - ./CA/certificate.pem:/app/certificate.pem
      - ./CA/private_key.pem:/app/private_key.pem

  httpapp:
    build:
      context: ./app
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro